version: "3.1"
services:
  apache:
    image: php:8.1-apache-bullseye 
    container_name: php 
    build: .
    volumes:
      - type: bind
        source: ./public/
        target: /var/www/html 
    ports:
      - "80:80"
    environment:
      - POST_ID=68957
